### ISSUE TITLE
Issue in the modlAMP example script for peptide classification

### ISSUE THREAD

**Issue by souravsingh** [alexarnimueller/modlAMP#1]
@alexarnimueller There are a few issues in the example script for peptide classification. Like in Line 17, it shows a NameError for ``desc``.

I have made some fixes to the script. Should I send a PR for the same?

**Comment by alexarnimueller** [comment]
hi @souravsingh! I'm sorry, didn't pay attention to the example scripts lately. The name typo should be fixed now. Thanks for letting me know! Enjoy modlamp!
