### ISSUE TITLE
Difficulty in Analysis of Different Sequence Libraries

### ISSUE THREAD

**Issue by sandeep5sep** [alexarnimueller/modlAMP#10]
Dear Sir
I am using modlamp.analysis module for analysing the peptide sequence dataset. I am able to run the **g = GlobalAnalysis(['GLFDIVKKVVGALG', 'KLLKLLKKLLKLLK', ...], names=['Library1'])**  for amino acid frequency calculation and summary plot but facing difficulty in inputting the dataset as dataframe.

I converted csv file into dataframe but was not able to do analysis using  above commands. i am getting the syntax error. Can you please guide me how to use dataframe in above script.
furthermore, I want to ask whether **Analysis of Different Sequence Libraries** only takes input in form of list/array only. If yes, how can i use my peptide dataframe dataset to do analysis.
I have 3 libraries of peptide in form of column.

Please help
Regards
Sandeep

**Comment by alexarnimueller** [comment]
Hi Sandeep
Sorry that it took me 11 days ;-)
So I assume you do have a pandas dataframe with a column containing sequences, right?
so how I would do it is as such:

`import pandas as pd`
`from modlamp.analysis import GlobalAnalysis`

`df = pd.DataFrame({'Sequence': ['GLFDIVKKVVGALG', 'KLLKLLKKLLKLLK']})  # dataframe just for testing, insert your own here`
`a = GlobalAnalysis(df['Sequence'], names=['Library1'])`
`a.calc_aa_freq()`
`a.aafreq`

Let me know whether this works in your case.

Best,
Alex

**Comment by alexarnimueller** [comment]
@sandeep5sep is it OK for you if I close this issue now?

**Comment by sandeep5sep** [comment]
Dear Sir
First of all, thanks to your reply.  

Sir, i am able to run the above script but the problem is that the peptide data is large and is in a excel sheet CSV format which i converted in to dataframe for further analysis. The excel sheet contains peptides in three columns designated as library1, library2 and library3.

**df = pd.DataFrame({'Sequence': ['GLFDIVKKVVGALG', 'KLLKLLKKLLKLLK']}**
If i used above script, i have to give all peptide in the brackets but for a large dataset that i have it may look little bit fuzzy.

can there is any way of providing input of all three peptide libraries for global analysis through the dataframe. 

Regards
Sandeep

**Comment by alexarnimueller** [comment]
Hi Sandeep
First, upgrade to the latest modlamp version (4.1.2): `pip install --upgrade modlamp`
I have fixed some bugs in the plotting.

**About you issue with the pandas dataframe:**
You have to provide the sequences in lists or arrays.
So if you have a pandas dataframe `df` with three columns you can do this:

`a = GlobalAnalysis(df.values.T, names=df.columns.values)`

To then generate the summary plot, do:

`a.plot_summary()`

Good luck!

**Comment by alexarnimueller** [comment]
Hi Sandeep

I just took the time to implement that you can just feed your pandas dataframe to the GlobalAnalyis class:

`a = GlobalAnalysis(df)`
`a.plot_summary()`

That should work now. Let me know if it works and I'll close the issue.

Cheers
