### ISSUE TITLE
pips internal functions issue while building biocoda package 

### ISSUE THREAD

**Issue by jaidevjoshi83** [alexarnimueller/modlAMP#11]
I have successfully added modlamp==4.1.2 to bioconda, however, while I am trying to build a package for 4.1.4 the latest release it's showing an error given below while building the conda package. The similar error I  also experience while I am trying to install modlamp==4.1.4 using pip to my local computer and install failed eventually. 

13:22:46 BIOCONDA INFO (OUT) Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-u0iC5E'
13:22:46 BIOCONDA INFO (OUT) Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
13:22:46 BIOCONDA INFO (OUT) Running command python setup.py egg_info
13:22:46 BIOCONDA INFO (OUT) Created temporary directory: /tmp/pip-pip-egg-info-hJByB2
13:22:46 BIOCONDA INFO (OUT) Traceback (most recent call last):
13:22:46 BIOCONDA INFO (OUT) File "<string>", line 1, in <module>
13:22:46 BIOCONDA INFO (OUT) File "/opt/conda/conda-bld/modlamp_1588166316542/work/setup.py", line 11, in <module>
13:22:46 BIOCONDA INFO (OUT) reqs = [str(ir.req) for ir in install_reqs][:-1]
13:22:46 BIOCONDA INFO (OUT) AttributeError: 'ParsedRequirement' object has no attribute 'req'

details can be found on this "https://github.com/bioconda/bioconda-recipes/pull/21839" 

After discussing this issue with Bioconda community, it looks like some pip's internal functions have been used that will break over time. resolve this issue will help to build this package for conda.

**Comment by alexarnimueller** [comment]
Hi jaidevjoshi83

That's great. I just did fix some bugs and modlAMP is now version 4.2.1.
Is the error still appearing?

Cheers

**Comment by dpryan79** [comment]
Please do not use pip's internal functions, they are not intended for use by other packages. modlAMP is still broken in version 4.2.1 in bioconda because pip's internal structure has changed.

Xref: https://github.com/bioconda/bioconda-recipes/pull/21839

**Comment by alexarnimueller** [comment]
sorry, my fault. Removed now, let's see

**Comment by jaidevjoshi83** [comment]
Thank you for rectifying the problem.
