### ISSUE TITLE
plot.py plot_aa_distr bug

### ISSUE THREAD

**Issue by delphinas** [alexarnimueller/modlAMP#12]
Hi,

There is a bug within plot.py, function plot_aa_distr. It should be as it used to be:

```
for a in range(20):
  plt.bar(a, list(aa.values())[a], 0.9, color=color)
```

Rather than (680-682):
```
for i, v in enumerate([k for k, w in aa.items()]):
  plt.bar(i, v, 0.9, color=color)
```

Vito

**Comment by alexarnimueller** [comment]
Hi Vito
Thanks for pointing this out! No idea what happened there...
Anyways, it's fixed now in 4.2.1 and ready to be updated from pip.
Cheers
Alex
