### ISSUE TITLE
Improve documentation for descriptors.GlobalDescriptor

### ISSUE THREAD

**Issue by hejops** [alexarnimueller/modlAMP#13]
https://modlamp.org/modlamp.html#modlamp.descriptors.GlobalDescriptor.calculate_all

The method `descriptors.GlobalDescriptor` returns an array of 10 elements (everything except molecular formula). However, the documented example shows an array of 9 elements; sequence charge is missing. This was quite baffling to me when I first used the method.

The documentation could be written as such for better clarity:
"Method combining all 10 global descriptors (except molecular formula)..."

**Comment by alexarnimueller** [comment]
Hi @hejops, thanks a lot for pointing this out. The documentation wasn't adapted when we changed the code.
Btw: the feature names corresponding to the descriptor values can be obtained from the attribute `featurenames`.
I will correct the documentation with the next version.
Cheers

**Comment by alexarnimueller** [comment]
The documentation is corrected and there is also a new version 4.3.0 available for update. Have fun
`pip install --upgrade modlamp`
