### ISSUE TITLE
For the pepCATS descriptor, are the bit patterns listed somewhere?

### ISSUE THREAD

**Issue by UnixJunkie** [alexarnimueller/modlAMP#14]
Hello,
In the code, is there a table giving the bit pattern for each of the 20 amino acids?
I looked in the code but couldn't find it.
Thanks a lot,
F.

**Comment by alexarnimueller** [comment]
Hi F
Yes, the scales are defined in the function `load_scale​(​scalename​)` in modlamp.core on line 803.
Hope that helps

**Comment by UnixJunkie** [comment]
Ok, on line 887 I see the pepCATS bit patterns. Thanks!

**Comment by UnixJunkie** [comment]
I could not find those initially because github's search is case-sensitive and I was looking for 'pepCATS'...

**Comment by alexarnimueller** [comment]
Ah OK that's good to know, thanks
