### ISSUE TITLE
Running SVM on AMP vs UniProt shows an error.

### ISSUE THREAD

**Issue by souravsingh** [alexarnimueller/modlAMP#2]
@alexarnimueller  I am getting an error on running the AMP classification using SVM.

```
Traceback (most recent call last):
  File "classify-amp.py", line 27, in <module>
    lib.generate_sequences()
  File "/home/ssouravsingh12/.local/lib/python2.7/site-packages/modlamp/sequences.py", line 536, in generate_sequences
    H.generate_sequences()
  File "/home/ssouravsingh12/.local/lib/python2.7/site-packages/modlamp/sequences.py", line 136, in generate_sequences
    seq = ['X'] * random.choice(range(self.lenmin, self.lenmax + 1))
  File "mtrand.pyx", line 1121, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17200)
ValueError: a must be non-empty
```

**Comment by alexarnimueller** [comment]
can you further specify what you are doing? 
I assume the error does araise from generating sequences. You need to specify a library enough big in size to achieve a good distribution. Otherwise just use sequences from a sub-class, e.g. Helices(1000)

**Comment by souravsingh** [comment]
I was trying to run the example given here- https://github.com/alexarnimueller/modlAMP/blob/master/bin/example_modlamp.rst
using SVM as a parameter for ``train_best_model``

**Comment by alexarnimueller** [comment]
I just ran the script with SVM and it works fine for me. It seems that you might have a problem with your random state. Try adding

import numpy as np
np.random.seed(42)

at the beginning of your script. 

Second option: change libsize to 10000

**Comment by souravsingh** [comment]
Thanks, I will take a look.

Another question unrelated to the issue- Is there a plan for the library to support Python 3, since Python 2.7 is reading end of life in 2020?

**Comment by alexarnimueller** [comment]
Yes, I am working on the Python 3 compatibility. Did you try to run it on Python 3? It might actually already work

**Comment by souravsingh** [comment]
I haven't checked it.  Thanks for the help!

Closing the issue.
