### ISSUE TITLE
Issue in obtaining descriptors for FASTA data

### ISSUE THREAD

**Issue by souravsingh** [alexarnimueller/modlAMP#4]
Hello @alexarnimueller 

I am having an issue in obtaining the descriptor data for the FASTA data here- http://caps.ncbs.res.in/3dswap-pred/data/3dswap-pred_positive_dataset.fasta

Here is the program I am running-

```python
from modlamp.descriptors import PeptideDescriptor
pepdesc = PeptideDescriptor('3dswap-pred_negative_dataset.fasta', 'eisenberg') 
pepdesc.calculate_global()
pepdesc.calculate_moment(append=True)  
pepdesc.load_scale('z3')
pepdesc.calculate_autocorr(1, append=True)
col_names = 'ID,Sequence,H_Eisenberg,uH_Eisenberg,Z3_1,Z3_2,Z3_3'
pepdesc.save_descriptor('neg_descriptors1.csv', header=col_names)
```

I am obtaining this error-

```
Traceback (most recent call last):
  File "desc_negative.py", line 8, in <module>
    pepdesc.calculate_global()  # calculate global Eisenberg hydrophobicity
  File "/usr/local/lib/python2.7/dist-packages/modlamp/descriptors.py", line 802, in calculate_global
    mtrx.append(self.scale[str(seq[l])])
KeyError: 'X'
```

**Comment by alexarnimueller** [comment]
Hi Sourav

It seems that you have peptides in your dataset with unknown amino acids (X).
Currently, modlAMP can only handle natural amino acids. So either remove these sequences or change the X to a natural amino acid.

Regards
Alex

**Comment by souravsingh** [comment]
Thanks a lot for your help. I have eliminated the sequences from the file. Closing the issue
