### ISSUE TITLE
Incorrect formula for Glutamine using GlobalDescriptor

### ISSUE THREAD

**Issue by david-cox-sciex** [alexarnimueller/modlAMP#9]
Using the code
desc = GlobalDescriptor(['Q'])
desc.formula(amide=False)
for v in desc.descriptor:
     print(v[0])

I get:
C4 H7 N1 O4

The correct formula for Glutamine is:
C5H10N2O3

**Comment by alexarnimueller** [comment]
hi david
thanks a lot for recognizing this bug. I have changed it and updated to version 4.1.1
